name: The Bill Myers Show
favicon: null
layout_spectrum: 0.6526199856307358
typography_spectrum: 0.9034420598763973
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9705909513868392
  lightness: 0.8249554308131337
  saturation: 0.1366565371863544
  rhythmicContrast: 0.8904560646042228
purpose: []
